#!/bin/bash
#This install making for ur linux bundle of special programs
USER=$(logname)
cd .. && chown -R $USER deb && cd deb
dpkg -i refind_0.13.2-1_amd64.deb && dpkg -i ferdi_5.6.3_amd64.deb && dpkg -i franz_5.7.0_amd64.deb && dpkg -i google-chrome-stable_current_amd64.deb && dpkg -i protonvpn-stable-release_1.0.1-1_all.deb
apt-get update
apt-get install protonvpn
apt install gnome-shell-extension-appindicator gir1.2-appindicator3-0.1
grep '/usr/s\?bin' /etc/systemd/system/display-manager.service
cd ..
