#!/bin/bash
#This install making for ur linux bundle of special programs
USER=$(logname)
cd .. && cd tar
chown $USER teleg.tar.xz && chown $USER tor.tar.xz
tar xf teleg.tar.xz -C ../../Software
tar xf tor.tar.xz -C ../../Software
cd .. && chown -R $USER tar
cd .. && chown -R $USER Software && cd Software
chmod +x Telegram/* && chmod 777 tor-browser_en-US/*
cd tor-browser_en-US
chmod +x start-tor-browser.desktop && su amnesia && ./start-tor-browser.desktop --register-app
cd ../../ && cd mnsinstall && cd scripts



