#!/bin/bash
USER=$(logname)
cd ../../ && mkdir /home/$USER/Software && chmod 777 /home/$USER/Software
cd mnsinstall && cd run
chown $USER vipole.x86_64.run && chmod +x vipole.x86_64.run
echo "Install VIPole in /home/%USERNAME%/Software"
./vipole.x86_64.run
cd .. && cd scripts

